Imported Upstream version 2.4.3

diff --git a/man/ganeti-os-interface.7.in b/man/ganeti-os-interface.7.in
--- a/man/ganeti-os-interface.7.in
+++ b/man/ganeti-os-interface.7.in
@@ -246,12 +246,12 @@ verification script could be:
       #!/bin/sh
       
       case\ $OSP_DHCP\ in
-      \ \ \ \ ""|yes|no)
-      \ \ \ \ \ \ \ \ ;;
-      \ \ \ \ *)
-      \ \ \ \ \ \ \ \ echo\ "Invalid\ value\ \[aq]$OSP_DHCP\[aq]\ for\ the\ dhcp\ parameter"\ 1>&2
-      \ \ \ \ \ \ \ \ exit\ 1;
-      \ \ \ \ \ \ \ \ ;;
+      \ \ ""|yes|no)
+      \ \ \ \ \ \ ;;
+      \ \ *)
+      \ \ \ \ echo\ "Invalid\ value\ \[aq]$OSP_DHCP\[aq]\ for\ the\ dhcp\ parameter"\ 1>&2
+      \ \ \ \ exit\ 1;
+      \ \ \ \ ;;
       esac
       
       exit\ 0
