prerm script fixes
 • Do not exit before any debhelper snippets run.
 • Use test -ef instead of readlink (dash built-in).
 • Check /usr/lib/ganeti/default instead of /etc/ganeti/lib.
 • Fix typos (!= "remove" -> = "remove").

diff --git a/debian/ganeti-htools-VER.prerm b/debian/ganeti-htools-VER.prerm
--- a/debian/ganeti-htools-VER.prerm
+++ b/debian/ganeti-htools-VER.prerm
@@ -2,26 +2,23 @@
 
 set -e
 
-if [ "$1" != "remove" ]; then
-	exit 0;
-fi
+if [ "$1" = "remove" ]; then
+	. /usr/share/debconf/confmodule
 
-. /usr/share/debconf/confmodule
+	if [ /usr/lib/ganeti/default -ef /usr/lib/ganeti/VER ]; then
+	       db_version 2.0
+	       db_fset ganeti-htools-VER/abort-removal seen false
+	       db_subst ganeti-htools-VER/abort-removal version VER
+	       db_subst ganeti-htools-VER/abort-removal package ganeti-htools-VER
+	       db_input critical ganeti-htools-VER/abort-removal
+	       db_go
+	       db_get ganeti-htools-VER/abort-removal
 
-target=$(readlink /etc/ganeti/lib || true)
-if [ "$target" = "/usr/lib/ganeti/VER" ]; then
-       db_version 2.0
-       db_fset ganeti-htools-VER/abort-removal seen false
-       db_subst ganeti-htools-VER/abort-removal version VER
-       db_subst ganeti-htools-VER/abort-removal package ganeti-htools-VER
-       db_input critical ganeti-htools-VER/abort-removal
-       db_go
-       db_get ganeti-htools-VER/abort-removal
-
-       if [ "$RET" = "true" ]; then
-	       echo "Aborting removal on user request"
-               exit 1;
-       fi
+	       if [ "$RET" = "true" ]; then
+		       echo "Aborting removal on user request"
+		       exit 1;
+	       fi
+	fi
 fi
 
 #DEBHELPER#
